### ISSUE TITLE
new user

### ISSUE THREAD

**Issue by iokk** [wfce/ChatGPT-OpenAI-API#1]
name: imioio

**Comment by wfce** [comment]
微信点此扫一扫二维码或微信搜索“AI最新地址”公众号获取更多最新地址防封 - 购买CHAKEY后可使用VIP版TDChatVIP线路一：https://tdchatvip.usVIP线路二：https://tdvip.usTDChat普通版入口地址：http://tdchat.ukhttp://t-d.chat

**Comment by wfce** [comment]
> name: imioio

star
