### ISSUE TITLE
new user

### ISSUE THREAD

**Issue by PM-pinou** [wfce/ChatGPT-OpenAI-API#2]
name:2504420230

**Comment by wfce** [comment]
微信点此扫一扫二维码或微信搜索“AI最新地址”公众号获取更多最新地址防封 - 购买CHAKEY后可使用VIP版TDChatVIP线路一：https://tdchatvip.usVIP线路二：https://tdvip.usTDChat普通版入口地址：http://tdchat.ukhttp://t-d.chat

**Comment by PM-pinou** [comment]
好的OK
![01A9B15B](https://github.com/wfce/ChatGPT-OpenAI-API/assets/89000707/419fc824-cf2d-450b-85ac-26bd86e2ec79)

**Comment by wfce** [comment]
已送
